name: Pull

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Thank you for creating your first pull request! The official @BeatableMeat account will take a look at this soon. If it is a good enough feature, it will be merged.'
