name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your Issue. A Collaborator will label this and have a look soon.'
        pr-message: 'Thank you for submitting your Pull Request. A Collaborator will label this and have a look soon.'
