name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating your first issue! A moderator (their username will end with "-heatwave" or "-phoenix") will label your issue soon and make any changes to it if needed.'
        pr-message: 'Thank you for creating your first pull request! The official @BeatableMeat account will take a look at this soon. If it is a good enough feature, it will be merged.'
